version: '3.8'

services:
  # Phiên bản nặng (Standard)
  nest-heavy:
    build:
      context: .
      dockerfile: Dockerfile.standard
    container_name: nest-heavy-app
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production

  # Phiên bản tối ưu (Optimize)
  nest-slim:
    build:
      context: .
      dockerfile: Dockerfile.optimize
    container_name: nest-slim-app
    ports:
      - '3002:3000'
    environment:
      - NODE_ENV=production
